export const policiesInfo = [
    {
        header:   'CollabPolicies' ,
        info: [
            { id: 'policy-title', title: 'chính sách cộng tác viên' },
            { id: 'policy-type', text: <><b>Kiểu chính sách</b> với 1 trong 2 kiểu chính sách có thể áp dụng là:</> },
            { id: 'general-policy', text: <><b>Chính sách hoa hồng chung:</b> là chính sách áp dụng cho toàn bộ sản phẩm trên website ngoại trừ đi các sản phẩm có mức hoa hồng đặc biệt thiết lập tại mục “Chính sách hoa hồng theo sản phẩm”. Khi đối tác giới thiệu các đơn hàng chỉ chứa sản phẩm thông thường (không nằm trong danh sách sản phẩm có hoa hồng đặc biệt) thì sẽ được tính toán mức hoa hồng như chính sách chung. Để thiết lập chính sách hoa hồng chung, bạn cần chọn:</> },
            { id: 'percentage-commission', text: <>% hoa hồng theo giá trị đơn hàng</> },
            { id: 'applicable-value', text: <>Và <b>Giá trị đơn hàng áp dụng</b> theo:</> },
            { id: 'fixed-value', text: <>Số tiền cố định theo mỗi đơn hàng</> },
            { id: 'total-value-no-ship', text: <>Tổng giá trị đơn hàng không có phí vận chuyển: hoa hồng của đối tác được tính trên tổng giá trị đơn hàng trừ đi phí vận chuyển</> },
            { id: 'total-value-with-ship', text: <>Tổng giá trị đơn hàng bao gồm phí vận chuyển: Hoa hồng của đối tác sẽ được tính trên tổng giá trị đơn hàng có bao gồm phí vận chuyển</> },
            { id: 'product-policy', text: <><b>Chính sách hoa hồng theo sản phẩm</b> (Tùy chọn): là chính sách chỉ áp dụng cho 1 danh sách sản phẩm hay danh mục sản phẩm tùy chọn. Khi đơn hàng chỉ chứa các sản phẩm có mức hoa hồng đặc biệt thì sẽ áp dụng mức hoa hồng được thiết lập cho từng sản phẩm để tính ra mức hoa hồng cho đối tác. Để thiết lập chính sách hoa hồng theo sản phẩm bạn cần:</> },
            { id: 'select-product', text: <><b>Lựa chọn sản phẩm</b>, bạn có thể chọn đích danh 1 sản phẩm cụ thể hoặc chọn cả danh mục sản phẩm</> },
            { id: 'commission-type', text: <>Chọn loại <b>Hoa hồng áp dụng:</b> Theo phần trăm (%) hoặc Theo số tiền (đ)</> },
            { id: 'confirm-setup', text: <>Tiếp theo, bạn chọn <b>Xác nhận</b> để hoàn tất thiết lập chính sách hoa hồng cho sản phẩm</> },
            { id: 'post-setup', text: <>Sau khi<b> Xác nhận</b>, sản phẩm / danh mục sản phẩm thuộc chính sách hoa hồng theo sản phẩm sẽ hiển thị ở mục <b>Danh sách hoa hồng theo sản phẩm</b></> },
            { id: 'closing-remark', text: <><b>Trân Trọng!</b></> },
        ]
    },
    {
        header:  'ExchangePolicies' ,
        info: [
            { id: 'policy-title', title: 'chính sách đổi sản phẩm' },
            { id: 'policy-reason-production', text: <>+ Sản phẩm lỗi, hỏng do quá trình sản xuất hoặc vận chuyển</> },
            { id: 'policy-reason-return-policy', text: <>+ Nằm trong chính sách đổi trả sản phẩm của Bean</> },
            { id: 'policy-condition-untouched', text: <>+ Sản phẩm còn nguyên tem mác chưa qua sử dụng và chưa giặt là</> },
            { id: 'policy-time-limit', text: <>+ Thời gian đổi trả nhỏ hơn 15 ngày kể từ ngày nhận hàng</> },
            { id: 'policy-costs', text: <>+ Chi phí bảo hành về sản phẩm, vận chuyển khách hàng chịu chi phí</> },
            { id: 'policy-vip-support', text: <>+ Đối với khách VIP thì khi đổi trả Bean sẽ hỗ trợ miễn phí quá trình đổi trả, sửa chữa</> },
            { id: 'policy-condition-header', text: <><b>Điều kiện đổi trả hàng:</b></> },
            { id: 'policy-condition-intact', text: <>- Sản phẩm gửi lại phải còn nguyên đai nguyên kiện</> },
            { id: 'policy-condition-warranty', text: <>- Phiếu bảo hành (nếu có) và tem của công ty trên sản phẩm còn nguyên vẹn.</> },
            { id: 'policy-condition-accessories', text: <>- Sản phẩm đổi/ trả phải còn đầy đủ hộp, giấy Hướng dẫn sử dụng và chưa qua sử dụng.</> },
            { id: 'policy-condition-costs', text: <>- Quý khách chịu chi phí vận chuyển, đóng gói, thu hộ tiền, chi phí liên lạc tối đa tương đương 20% giá trị đơn hàng.</> },
            { id: 'policy-process-header', text: <><b>Quy trình đổi trả hàng</b></> },
            { id: 'policy-process-step1', text: <>Bước 1: Sau khi nhận được hàng. Yêu cầu quý vị kiểm tra kỹ 1 lần trước khi nhận hàng. Nếu có vấn đề xin vui lòng liên hệ Trung tâm hỗ trợ khách hàng tại thời điểm nhân viên giao hàng còn ở đó</> },
            { id: 'policy-process-after-delivery', text: <>- Trường hợp sau khi nhân viên giao hàng đã đi</> },
            { id: 'policy-process-contact-us', text: <>- Nếu muốn đổi trả hàng có thể liên hệ với chúng tôi để được xử lý và hẹn lịch đổi trả hàng</> },
            { id: 'policy-process-step2', text: <>Bước 2: Sau khi Trung tâm hỗ trợ khách hàng thông báo lịch hẹn nhận hàng trả</> },
        ]
    },
    {
        header:  'MembershipPolicies' ,
        info: [
            { id: 'policy-title', title: 'chính sách thành viên' },
            { id: 'policy-conditions', text: <>Điều kiện chính sách thành viên</> },
            { id: 'policy-member-card', text: <><b>1. Thẻ thành viên</b></> },
            { id: 'policy-member-card-condition', text: <>Điều kiện cấp thẻ thành viên: Khi khách hàng mua hàng trên hệ thống cửa hàng Bean Fashion sẽ được cấp thẻ thành viên</> },
            { id: 'policy-vip-card', text: <><b>2. Thẻ VIP</b></> },
            { id: 'policy-vip-condition-header', text: <><b>Điều kiện nhận thẻ VIP:</b></> },
            { id: 'policy-vip-condition-total', text: <>+ Có giá trị tổng đơn hàng lớn hơn 15 triệu/ tháng</> },
            { id: 'policy-vip-condition-single', text: <>+ Mua hàng với giá trị 5 triệu trở lên</> },
            { id: 'policy-vip-condition-events', text: <>+ Tham gia các hoạt động, chương trình khuyến mãi của Bean</> },
            { id: 'policy-note', text: <><b>Lưu ý: </b>Hạn mức 10, 20, 30, 50, 100 triệu đồng là tính từ thời điểm bắt đầu mua tới khi lên thẻ. Khi lên thẻ VIP và tích tiếp lên 20 đến 100 triệu, tổng tiền này là tính từ khi khách hàng mua lần đầu và cộng dồn lên</> },
        ]
    },
    {
        header:  'PaymentPolicies' ,
        info: [
            { id: 'policy-title', title: 'Chính sách thanh toán' },
            { id: 'policy-payment-instore-header', text: <><b>Khách hàng thanh toán trực tiếp tại cửa hàng</b></> },
            { id: 'policy-payment-instore-discount', text: <>+ Nhận ưu đãi</> },
            { id: 'policy-payment-instore-gift', text: <>+ Nhận quà tặng kèm</> },
            { id: 'policy-payment-instore-checkin', text: <>+ Checkin tại cửa hàng</> },
            { id: 'policy-payment-online-header', text: <><b>Khách hàng thanh toán online</b></> },
            { id: 'policy-payment-online-transfer', text: <>+ Chuyển khoản trước khi nhận hàng</> },
            { id: 'policy-payment-online-gift', text: <>+ Quà tặng kèm bất kỳ</> },
            { id: 'policy-complaint', text: <>Khách hàng có nhu cầu khiếu nại, đổi trả sản phẩm do lỗi của Bean có thể liên hệ qua Hotline 1900 6750 để được hỗ trợ sớm nhất.</> },
            { id: 'policy-refund-process', text: <>Tư vấn viên sẽ hướng dẫn khách hàng các bước cần thiết để tiến hành trả thanh toán.</> },
        ]
    },
    {
        header:  'PurchasePolicies' ,
        info: [
            { id: 'guide-title', title: 'Hướng dẫn mua hàng' },
            { id: 'guide-step-1', text: <><b>Bước 1:</b> Truy cập website và lựa chọn sản phẩm cần mua để mua hàng</> },
            { id: 'guide-step-2', text: <><b>Bước 2:</b> Click và sản phẩm muốn mua, màn hình hiển thị ra pop up với các lựa chọn sau</> },
            { id: 'guide-step-2-continue-shopping', text: <>Nếu bạn muốn tiếp tục mua hàng: Bấm vào phần tiếp tục mua hàng để lựa chọn thêm sản phẩm vào giỏ hàng</> },
            { id: 'guide-step-2-view-cart', text: <>Nếu bạn muốn xem giỏ hàng để cập nhật sản phẩm: Bấm vào xem giỏ hàng</> },
            { id: 'guide-step-2-checkout', text: <>Nếu bạn muốn đặt hàng và thanh toán cho sản phẩm này vui lòng bấm vào: Đặt hàng và thanh toán</> },
            { id: 'guide-step-3', text: <><b>Bước 3:</b> Lựa chọn thông tin tài khoản thanh toán</> },
            { id: 'guide-step-3-login', text: <>Nếu bạn đã có tài khoản vui lòng nhập thông tin tên đăng nhập là email và mật khẩu vào mục đã có tài khoản trên hệ thống</> },
            { id: 'guide-step-3-register', text: <>Nếu bạn chưa có tài khoản và muốn đăng ký tài khoản vui lòng điền các thông tin cá nhân để tiếp tục đăng ký tài khoản. Khi có tài khoản bạn sẽ dễ dàng theo dõi được đơn hàng của mình</> },
            { id: 'guide-step-3-guest-checkout', text: <>Nếu bạn muốn mua hàng mà không cần tài khoản vui lòng nhấp chuột vào mục đặt hàng không cần tài khoản</> },
            { id: 'guide-step-4', text: <><b>Bước 4:</b> Điền các thông tin của bạn để nhận đơn hàng, lựa chọn hình thức thanh toán và vận chuyển cho đơn hàng của mình</> },
            { id: 'guide-step-5', text: <><b>Bước 5:</b> Xem lại thông tin đặt hàng, điền chú thích và gửi đơn hàng</> },
            { id: 'guide-confirmation', text: <>Sau khi nhận được đơn hàng bạn gửi chúng tôi sẽ liên hệ bằng cách gọi điện lại để xác nhận lại đơn hàng và địa chỉ của bạn.</> },
            { id: 'guide-thanks', text: <>Trân trọng cảm ơn.</> },
        ]
    },
    {
        header:  'SecurityPolicies' ,
        info: [
            { id: 'privacy-title', title: 'Bảo mật thông tin cá nhân' },
            { id: 'privacy-intro-1', text: <>Cám ơn quý khách đã quan tâm và truy cập vào website. Chúng tôi tôn trọng và cam kết sẽ bảo mật những thông tin mang tính riêng tư của Quý khách.</> },
            { id: 'privacy-intro-2', text: <>Chính sách bảo mật sẽ giải thích cách chúng tôi tiếp nhận, sử dụng và (trong trường hợp nào đó) tiết lộ thông tin cá nhân của Quý khách.</> },
            { id: 'privacy-intro-3', text: <>Bảo vệ dữ liệu cá nhân và gây dựng được niềm tin cho quý khách là vấn đề rất quan trọng với chúng tôi. Vì vậy, chúng tôi sẽ dùng tên và các thông tin khác liên quan đến quý khách tuân thủ theo nội dung của Chính sách bảo mật. Chúng tôi chỉ thu thập những thông tin cần thiết liên quan đến giao dịch mua bán.</> },
            { id: 'privacy-intro-4', text: <>Chúng tôi sẽ giữ thông tin của khách hàng trong thời gian luật pháp quy định hoặc cho mục đích nào đó. Quý khách có thể truy cập vào website và trình duyệt mà không cần phải cung cấp chi tiết cá nhân. Lúc đó, Quý khách đang ẩn danh và chúng tôi không thể biết bạn là ai nếu Quý khách không đăng nhập vào tài khoản của mình.</> },
            { id: 'privacy-collection-title', text: <><b>1. Thu thập thông tin cá nhân</b></> },
            { id: 'privacy-collection-info', text: <>- Chúng tôi thu thập, lưu trữ và xử lý thông tin của bạn cho quá trình mua hàng và cho những thông báo sau này liên quan đến đơn hàng, và để cung cấp dịch vụ, bao gồm một số thông tin cá nhân: danh hiệu, tên, giới tính, ngày sinh, email, địa chỉ, địa chỉ giao hàng, số điện thoại, fax, chi tiết thanh toán, chi tiết thanh toán bằng thẻ hoặc chi tiết tài khoản ngân hàng.</> },
            { id: 'privacy-collection-use', text: <>- Chúng tôi sẽ dùng thông tin quý khách đã cung cấp để xử lý đơn đặt hàng, cung cấp các dịch vụ và thông tin yêu cầu thông qua website và theo yêu cầu của bạn.</> },
            { id: 'privacy-collection-account', text: <>- Hơn nữa, chúng tôi sẽ sử dụng các thông tin đó để quản lý tài khoản của bạn; xác minh và thực hiện giao dịch trực tuyến, nhận diện khách vào web, nghiên cứu nhân khẩu học, gửi thông tin bao gồm thông tin sản phẩm và dịch vụ. Nếu quý khách không muốn nhận bất cứ thông tin tiếp thị của chúng tôi thì có thể từ chối bất cứ lúc nào.</> },
            { id: 'privacy-collection-third-party', text: <>- Chúng tôi có thể chuyển tên và địa chỉ cho bên thứ ba để họ giao hàng cho bạn (ví dụ cho bên chuyển phát nhanh hoặc nhà cung cấp).</> },
            { id: 'privacy-collection-access', text: <>- Chi tiết đơn đặt hàng của bạn được chúng tôi lưu giữ nhưng vì lí do bảo mật nên chúng tôi không công khai trực tiếp được. Tuy nhiên, quý khách có thể tiếp cận thông tin bằng cách đăng nhập tài khoản trên web. Tại đây, quý khách sẽ thấy chi tiết đơn đặt hàng của mình, những sản phẩm đã nhận và những sản phẩm đã gửi và chi tiết email, ngân hàng và bản tin mà bạn đặt theo dõi dài hạn.</> },
            { id: 'privacy-collection-security', text: <>- Quý khách cam kết bảo mật dữ liệu cá nhân và không được phép tiết lộ cho bên thứ ba. Chúng tôi không chịu bất kỳ trách nhiệm nào cho việc dùng sai mật khẩu nếu đây không phải lỗi của chúng tôi.</> },
            { id: 'privacy-collection-research', text: <>- Chúng tôi có thể dùng thông tin cá nhân của bạn để nghiên cứu thị trường. Mọi thông tin chi tiết sẽ được ẩn và chỉ được dùng để thống kê. Quý khách có thể từ chối không tham gia bất cứ lúc nào.</> },
            { id: 'privacy-security-title', text: <><b>2. Bảo mật</b></> },
            { id: 'privacy-security-measures', text: <>- Chúng tôi có biện pháp thích hợp về kỹ thuật và an ninh để ngăn chặn truy cập trái phép hoặc trái pháp luật hoặc mất mát hoặc tiêu hủy hoặc thiệt hại cho thông tin của bạn.</> },
            { id: 'privacy-security-payment', text: <>- Chúng tôi khuyên quý khách không nên đưa thông tin chi tiết về việc thanh toán với bất kỳ ai bằng e-mail, chúng tôi không chịu trách nhiệm về những mất mát quý khách có thể gánh chịu trong việc trao đổi thông tin của quý khách qua internet hoặc email.</> },
            { id: 'privacy-security-interference', text: <>- Quý khách tuyệt đối không sử dụng bất kỳ chương trình, công cụ hay hình thức nào khác để can thiệp vào hệ thống hay làm thay đổi cấu trúc dữ liệu. Nghiêm cấm việc phát tán, truyền bá hay cổ vũ cho bất kỳ hoạt động nào nhằm can thiệp, phá hoại hay xâm nhập vào dữ liệu của hệ thống website. Mọi vi phạm sẽ bị tước bỏ mọi quyền lợi cũng như sẽ bị truy tố trước pháp luật nếu cần thiết.</> },
            { id: 'privacy-security-legal', text: <>- Mọi thông tin giao dịch sẽ được bảo mật nhưng trong trường hợp cơ quan pháp luật yêu cầu, chúng tôi sẽ buộc phải cung cấp những thông tin này cho các cơ quan pháp luật.</> },
            { id: 'privacy-legal-terms', text: <>Các điều kiện, điều khoản và nội dung của trang web này được điều chỉnh bởi luật pháp Việt Nam và tòa án Việt Nam có thẩm quyền xem xét.</> },
            { id: 'privacy-customer-rights-title', text: <><b>3. Quyền lợi khách hàng</b></> },
            { id: 'privacy-customer-rights', text: <>- Quý khách có quyền yêu cầu truy cập vào dữ liệu cá nhân của mình, có quyền yêu cầu chúng tôi sửa lại những sai sót trong dữ liệu của bạn mà không mất phí. Bất cứ lúc nào bạn cũng có quyền yêu cầu chúng tôi ngưng sử dụng dữ liệu cá nhân của bạn cho mục đích tiếp thị.</> },
        ]
    },
    {
        header:  'StockPolicies' ,
        info: [
            { id: 'policy-title', title: 'chính sách cộng tác viên' },
            { id: 'policy-wholesale-conditions', subTitle: '1. ĐIỀU KIỆN BÁN SỈ' },
            { id: 'policy-condition-1', text: <>- Chúng tôi cung cấp tất cả các mặt hàng có trên website chính thức</> },
            { id: 'policy-condition-2', text: <>- Mỗi đơn hàng từ 10 sản phẩm hoặc số lượng nhất định đối với các mặt hàng khác của chúng tôi bạn được tính ngay với giá bán buôn.</> },
            { id: 'policy-condition-3', text: <>- Kiểu dáng và màu sắc theo nhà sản xuất, một số mặt hàng đặc biệt sẽ theo yêu cầu của khách hàng.</> },
            { id: 'policy-condition-4', text: <>- Không áp dụng giá chung cho tất cả mặt hàng, tùy loại mặt hàng, giá bán sỉ sẽ tùy vào số lượng mua hàng.</> },
            { id: 'policy-condition-5', text: <>- Quý khách mua bao nhiêu chúng tôi sẽ báo giá bấy nhiêu, tùy theo từng lựa chọn của mỗi Quý khách.</> },
            { id: 'policy-wholesale-prices', subTitle: '2. CHÍNH SÁCH GIÁ BÁN SỈ' },
            { id: 'policy-price-1', text: <>- Chính sách giá bán sỉ được áp dụng cho khách hàng mua số lượng càng lớn thì giá càng tốt hơn.</> },
            { id: 'policy-price-2', text: <>- Quý khách mua số lượng nhiều hơn hoặc khách từng mua sỉ và lâu năm có thể liên hệ trực tiếp nhận báo giá cùng với nhiều ưu đãi đặc biệt.</> },
            { id: 'policy-wholesale-benefits', subTitle: '3. QUYỀN LỢI CỦA KHÁCH MUA SỈ' },
            { id: 'policy-benefit-1', text: <>- Chọn hàng trực tiếp tránh các mặt hàng lỗi - hư - rách do vận chuyển & lỗi của nhà sản xuất. Nếu Quý khách hàng ở Tỉnh khác hoặc ở Hà Nội & TP.HCM nhưng không có thời gian đến chúng tôi chọn mẫu thì chúng tôi sẽ hỗ trợ chụp hình thực tế từng món hàng quý khách đặt hoặc trực tuyến video cho quý khách kiểm tra trước khi đặt hàng</> },
            { id: 'policy-benefit-2', text: <>- Chúng tôi sẽ thông tin cho Quý khách khi có sản phẩm mới.</> },
            { id: 'policy-benefit-3', text: <>- Tất cả sản phẩm lấy tại hệ thống chúng tôi đều được cung cấp hình ảnh thực tế (nếu có nhu cầu).</> },
            { id: 'policy-benefit-4', text: <>- Miễn phí giao hàng tận nơi cho tất cả khách nội thành TP.HCM.</> },
            { id: 'policy-payment', subTitle: '4. THANH TOÁN' },
            { id: 'policy-payment-1', text: <>- Quý khách vui lòng thanh toán ngay khi giao hàng.</> },
            { id: 'policy-payment-2', text: <>- Với đơn hàng từ 20 triệu đồng trở lên và lấy hóa đơn, Quý khách được chuyển khoản khi thanh toán.</> },
            { id: 'policy-payment-3', text: <>- Quý khách vui lòng xem thêm phần chính sách vận chuyển để biết thêm chi tiết về thanh toán phí vận chuyển.</> },
        ]
    },
]